// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFGzI1NJI-LhJLh6sJEd6TWlf1TwmC7c',
    appId: '1:978413005637:web:526e1c2607a2728d926c2c',
    messagingSenderId: '978413005637',
    projectId: 'calender-app-d8f8a',
    authDomain: 'calender-app-d8f8a.firebaseapp.com',
    storageBucket: 'calender-app-d8f8a.appspot.com',
    measurementId: 'G-4BQ1684JZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe46t5oHrzVRtPv0ElgO4Lg6HJRgLwwZA',
    appId: '1:978413005637:android:884fdd9de94f0712926c2c',
    messagingSenderId: '978413005637',
    projectId: 'calender-app-d8f8a',
    storageBucket: 'calender-app-d8f8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_HgkWjlm7mPo7CdD4vnSID5Ud42xTS8Y',
    appId: '1:978413005637:ios:13a834112b0b1d10926c2c',
    messagingSenderId: '978413005637',
    projectId: 'calender-app-d8f8a',
    storageBucket: 'calender-app-d8f8a.appspot.com',
    iosBundleId: 'com.popupbits.flutterEvents2023',
  );
}
